{% set name = "fsl-sub-plugin-sge" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsl_sub_plugin_sge-{{ version }}.tar.gz
  sha256: dccd61d63e5bd99efa8dee8fe91b0327b93420e766d92dfebbe0ac52913785ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fsl-sub >=2.7.0
    - ruamel.yaml >=0.16.7

test:
  imports:
    - fsl_sub_plugin_sge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_sge
  summary: FSL Cluster Submission Plugin for Son of/Univa Grid Engine
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_sge
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauldmccarthy
